
# ======================================================================================================================
# ======================================================================================================================
# # # #  Append to the end of the file created by zshrc
# #  CT - CUSTOMIZED

# Set aliases
source ~/.alias

# Set the terminal style
export PS1="%B%F{226}%m%f%b %F{214}%n%f: %F{255}%1~$%f "

# Create New Folders with colored icons 
mkdir_r() {
    cp -R ~/PATH/TO/Folder_Templates/Red ./"$1"
}

mkdir_p() {
    cp -R ~/PATH/TO/Folder_Templates/Pink ./"$1"
}
mkdir_g() {
    cp -R ~/PATH/TO/Folder_Templates/Green ./"$1"
}
mkdir_o() {
    cp -R ~/PATH/TO/Folder_Templates/Orange ./"$1"
}
mkdir_y() {
    cp -R ~/PATH/TO/Folder_Templates/Yellow ./"$1"
}

# ======================================================================================================================
# # Browser Search Options

# Arc Browser Search and Tabs, room to improve the incognito functions
# google_search() {
#     local query=$(echo "$*" | sed 's/ /+/g')
#     osascript -e "tell application \"Arc\"
#         make new tab with properties {URL:\"https://google.com/search?q=$query\"}
#         activate
#     end tell"
# }
# 
# gs() {
#     local query=$(echo "$*" | sed 's/ /+/g')
#     osascript -e "tell application \"Arc\"
#         make new tab with properties {URL:\"https://google.com/search?q=$query\"}
#         activate
#     end tell"
# }
# 
# youtube_search() {
#     local query=$(echo "$*" | sed 's/ /+/g')
#     osascript -e "tell application \"Arc\"
#         make new tab with properties {URL:\"https://youtube.com/results?search_query=$query\"}
#         activate
#     end tell"
# }
# 
# # Ask ChatGPT a question
# chatGPT() {
#     local query=$(echo "$*" | sed 's/ /+/g')
#     osascript -e "tell application \"Arc\"
#         make new tab with properties {URL:\"https://chat.openai.com/chat?q=$query\"}
#         activate
#     end tell"
# }
# 
# arc_incog() {
#     osascript -e 'tell application "Arc"
#       make new window with properties {incognito:true}
#       activate
#     end tell'
# }

# # Superceded by Arc functions . . . Search Input on Google, in Chrome
# google_search() {
#     open -n -a "Google Chrome" --args "--new-tab" "https://google.com/search?q=$*"
# }
# # Search Input on Google, in Chrome in an Incognito tab
# google_search_incog() {
#     open -n -a "Google Chrome" --args "--incognito" "--new-tab" "https://google.com/search?q=$*"
# }  
# # Search Input on YouTube, in Chrome
# youtube_search() {
#     open -n -a "Google Chrome" --args "--new-tab" "https://youtube.com/results?search_query=$*"
# }
# # Search Input on YouTube, in Chrome in an incognito tab
# youtube_search_incog() {
#     open -n -a "Google Chrome" --args "--incognito"  "--new-tab" "https://youtube.com/results?search_query=$*"
# }
# # Ask ChatGPT a question
# chatGPT() {
#     open -n -a "Google Chrome" --args "--new-tab" "https://chat.openai.com/chat?q=$*"
# }

